# 非 host 版本, 不使用本机代理
version: '3.3'
services:
  pg:
    # image: ankane/pgvector:v0.4.2 # dockerhub
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # 阿里云
    container_name: pg
    restart: always
    #ports:
    # 生产环境建议不要暴露
    #- 5432:5432
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=fastgpt
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastgpt
    volumes:
      # 刚创建的文件
      - ./pg/init.sql:/docker-entrypoint-initdb.d/init.sh
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    # image: mongo:5.0.18
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    #ports:
    # 生产环境建议不要暴露
    #- 27017:27017
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/logs:/var/log/mongodb
  jydsgpt:
    container_name: jydsgpt
    # image: c121914yu/fast-gpt:latest # docker hub
    image: zq535228/jydsgpt:latest # 自己定义的
    # network_mode: host #
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always

  fastgpt-admin:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt-admin:latest
    container_name: fastgpt-admin
    restart: always
    ports:
      - 3001:3001
    networks:
      - fastgpt
    depends_on:
      - mongo
      - jydsgpt
    environment:
      - MONGODB_URI=mongodb://username:password@mongo:27017/?authSource=admin
      - MONGODB_NAME=fastgpt
      - ADMIN_USER=admin
      - ADMIN_PASS=z123456
      - ADMIN_SECRET=any
      - PARENT_URL=http://fastgpt:3000
      - PARENT_ROOT_KEY=root_key

  keyadmin:
    container_name: keyadmin
    image: justsong/one-api
    restart: always
    ports:
      - 3002:3000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./keyadmin:/data

networks:
  fastgpt:
